USE customer_behaviour;

-- Explore Our site-Map

/*Business Questions 
Q1. What is the total revenue generated by male customers compared to
female customers? 
Q2. Which customers used a discount but still spent more than the
company’s average purchase amount? 
Q3. Which five products have the highest average
customer review ratings? 
Q4. How does the average purchase amount compare between
customers using Standard shipping and those using Express shipping? 
Q5. Do subscribed customers spend more than non-subscribed customers in terms of both average spending and
total revenue contribution? 
Q6. Which five products have the highest percentage of purchases
made with discounts applied? 
Q7. How can customers be segmented into New, Returning, and
Loyal groups based on their previous purchases, and what is the size of each segment? 
Q8.What are the top three most purchased products within each product category? 
Q9. Are customers who are repeat buyers (more than five previous purchases) more likely to be
subscribed? 
Q10. How does total revenue contribution vary across different customer age
groups*/

SELECT *
FROM customers;

-- Q1. What is the total revenue generated by male customers compared to female customers?
SELECT gender,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the company’s average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied ='Yes'
    AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customers
        );

-- Q3.Which five products have the highest average customer review ratings?
SELECT item_purchased,
    ROUND(AVG(review_rating),1) AS "Product Rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. How does the average purchase amount compare between customers using Standard shipping and those using Express shipping?
SELECT shipping_type,
    ROUND(AVG(purchase_amount),1) AS Average_purchase_amount
FROM customers
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more than non-subscribed customers in terms of both average spending and total revenue contribution? 
SELECT subscription_status,
    AVG(purchase_amount) AS AVERAGE_SPENT,
    SUM(purchase_amount)AS TOTAL_REVENUE
FROM customers
GROUP BY subscription_status;

-- Q6. Which five products have the highest percentage of purchases made with discounts applied?
SELECT item_purchased,
    SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)
        / COUNT(*) * 100 AS Discount_rate 
FROM customers
GROUP BY item_purchased
ORDER BY Discount_rate DESC
LIMIT 5;

-- Q7. How can customers be segmented into New, Returning, and Loyal groups based on their previous purchases, and what is the size of each segment?
WITH customer_types AS
(
SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_Segment
FROM customers
)
SELECT customer_Segment, COUNT(*) AS Total_customers
FROM customer_types
GROUP BY customer_Segment;

-- Q8.What are the top three most purchased products within each product category? 
SELECT item_purchased,
    COUNT(*) AS total_purchased
FROM customers
GROUP BY item_purchased
ORDER BY total_purchased DESC
LIMIT 3;

WITH product_ranks AS
(
SELECT category, item_purchased,
    RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
FROM customers
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased
FROM product_ranks
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than five previous purchases) more likely to be subscribed?

-- Classify repeat buyers
SELECT
    subscription_status,
    CASE
        WHEN previous_purchases >5 THEN 'Repeat Buy'
        ELSE 'Non Repeat Buyer'
    END AS Buyer_Type,
    COUNT(customer_id) AS Total_Customer
FROM customers
GROUP BY subscription_status, Buyer_Type;

-- Subscription Rate (Stronger Answer)
   
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repead Buyer'
        ELSE 'Non Repeated Buy'
    END AS Buyer_Type,
    ROUND(
        SUM(CASE WHEN subscription_status = 'Yes'  THEN 1 ELSE 0 END) * 100.0 / COUNT(customer_id),2
    ) AS subscription_rate_percentage
FROM customers
GROUP BY Buyer_Type;

-- Q10. How does total revenue contribution vary across different customer age groups?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Optional: Average Spend by Age Group
SELECT
    age_group,
    COUNT(customer_id) AS total_Customer,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customers
GROUP BY age_group;

    